name: my_cv
description: Hey, I'm Joran.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  firebase_core: ^1.22.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.2.1
  image_downloader_web: ^1.0.2
  firebase_analytics: ^9.3.8
  easy_localization: ^3.0.1
  dropdown_button2: ^1.9.2
  download: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900